### ISSUE TITLE
KeyError: 'DOWNLOADED' when generate cosum dataset

### ISSUE THREAD

**Issue by semchan** [StevRamos/video_summarization#2]
Hi, I need to build cosum dataset use your code, but when I run "generate_dataset.py" on the raw dataset of cosum, it pop the error "KeyError: 'DOWNLOADED'". Would you please kinly help me?  Thanks a lot.

**Comment by StevRamos** [comment]
Hi @semchan , sorry for the late reply. I will update the repository during this week. I hope it helps you
