### ISSUE TITLE
Change points and user summary for TVSum dataset

### ISSUE THREAD

**Issue by TerboucheHacene** [StevRamos/video_summarization#4]
Hey Stev,

I am trying to understand you implementation to generate the dataset. In fact, for the TVSum, I compared the change points you made public with the ones from  KaiyangZhou's work. It seems like they are very different despite you are using the same features. I could be some differences in the parameters of the KTS algorithm, but I would like to have your insights. 

Second, to generate the user summary for the TVSum dataset, you are thresholding the ground truth scores. However, I think we should apply the knapsack algo on the GT scores to get the shots that belong to the summary.

Thanks for answering my concerns.

**Comment by StevRamos** [comment]
Hey Terbouche, sorry for the late reply. I missed this. But I hope I can help you. Regarding your first question, I think it also depends on the Python version. In fact, I couldn't replicate the results and I saw in several projects that they just used it and assumed it was correctly constructed. 

Second, yeah you are right. I made a simplified version but to be fair what you mentioned should be applied for TVSum dataset
